services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_APP=core/server.py
    command: ["gunicorn", "-c", "gunicorn_config.py", "core.server:app"]
    ports:
      - "7755:7755"
    volumes:
      - .:/app

